esphome:
  name: esphome-az32001
  friendly_name: esphome-az32001

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EhSrW6Bpn5IFA8VC2su/Q/Kr0G6ANdFq0+RZ4GJpJwg="

ota:
  password: "a2c799de5441ca15d610d0ef20f889bd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Az32001 Fallback Hotspot"
    password: "cqILzeyAAjaB"

captive_portal:

i2c: #(0x27,16,2) lcd1602 PCF8574T, 1=GND, 2=+5V, 3=SDA(orange)auf PIN13, 4=SCL(gelb)auf PIN14  (!PIN12 strapping pin not used)
  sda: GPIO32
  scl: GPIO33

sensor:
  - platform: dht
    pin: GPIO 26
    temperature:
      id: temp
      name: "Temperature Sensor 1Room "
    humidity:
      id: humi
      name: "Humidity Sensor 1Room "
    update_interval: 60s

#time:
 # - platform: homeassistant
 #   id: ha_time

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    update_interval: 60s 
    id: lcd
    lambda: |-
      it.printf(0, 0, "Temp: %.1f C", id(temp).state);
      it.printf(0, 1, "Humi: %.1f rel", id(humi).state);

binary_sensor:
  - platform: gpio
    pin: GPIO25 
    id: taster   
    on_press:
      then:
      - switch.toggle: my_led 
      - delay: 500ms
      - switch.toggle: my_led
      - delay: 500ms
      - switch.toggle: my_led
      - delay: 500ms
      - switch.toggle: my_led
      - delay: 500ms

switch:
  - platform: gpio
    pin: GPIO27
    id: my_led   
    name: LED27 am GPIO 
    